---
- name: Launch instance(s)
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - vars.yml
  - ["vars.{{ deployment_type }}.{{ cluster_id }}.yml", vars.defaults.yml]
  tasks:
  - fail:
      msg: Deployment type not supported for aws provider yet
    when: deployment_type == 'enterprise'

  - include: ../../common/openshift-cluster/set_master_launch_facts_tasks.yml
  - include: tasks/launch_instances.yml
    vars:
      instances: "{{ master_names }}"
      cluster: "{{ cluster_id }}"
      type: "{{ k8s_type }}"

  - include: ../../common/openshift-cluster/set_node_launch_facts_tasks.yml
  - include: tasks/launch_instances.yml
    vars:
      instances: "{{ node_names }}"
      cluster: "{{ cluster_id }}"
      type: "{{ k8s_type }}"

  - set_fact:
      a_master: "{{ master_names[0] }}"
  - add_host: name={{ a_master }} groups=service_master

- include: update.yml

- include: ../../common/openshift-cluster/create_services.yml
  vars:
     g_svc_master: "{{ service_master }}"

- include: list.yml
