---
g_template_heartbeat:
  name: Template Heartbeat
  zitems:
  - name: Heartbeat Ping
    applications:
    - Heartbeat
    key: heartbeat.ping
  ztriggers:
  - description: 'Heartbeat.ping has failed on {HOST.NAME}'
    expression: '{Template Heartbeat:heartbeat.ping.nodata(20m)}=1'
    priority: avg
