---
- name: restart master
  service: name={{ openshift.common.service_type }}-master state=restarted
  when: (not openshift_master_ha | bool) and (not master_service_status_changed | default(false))
