---
- name: Main List all templates
  zbx_template:
    zbx_server: "{{ ozb_server }}"
    zbx_user: "{{ ozb_user }}"
    zbx_password: "{{ ozb_password }}"
    state: list
  register: templates

- debug: var=templates

- include_vars: template_heartbeat.yml
- include_vars: template_os_linux.yml

- name: Include Template Heartbeat
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_heartbeat }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"

- name: Include Template os_linux
  include: ../../lib_zabbix/tasks/create_template.yml
  vars:
    template: "{{ g_template_os_linux }}"
    server: "{{ ozb_server }}"
    user: "{{ ozb_user }}"
    password: "{{ ozb_password }}"

