---
# TODO: fix firewall related bug with GCE and origin, since GCE is overriding
# /etc/sysconfig/iptables
- name: Populate oo_masters_to_config host group
  hosts: localhost
  gather_facts: no
  vars_files:
  - vars.yml
  tasks:
  - name: Evaluate oo_masters_to_config
    add_host:
      name: "{{ item }}"
      groups: oo_masters_to_config
      ansible_ssh_user: "{{ deployment_vars[deployment_type].ssh_user | default(ansible_ssh_user, true) }}"
      ansible_sudo: "{{ deployment_vars[deployment_type].sudo }}"
    with_items: groups["tag_env-host-type-{{ cluster_id }}-openshift-master"] | default([])
  - name: Evaluate oo_nodes_to_config
    add_host:
      name: "{{ item }}"
      groups: oo_nodes_to_config
      ansible_ssh_user: "{{ deployment_vars[deployment_type].ssh_user | default(ansible_ssh_user, true) }}"
      ansible_sudo: "{{ deployment_vars[deployment_type].sudo }}"
    with_items: groups["tag_env-host-type-{{ cluster_id }}-openshift-node"] | default([])
  - name: Evaluate oo_first_master
    add_host:
      name: "{{ groups['tag_env-host-type-' ~ cluster_id ~ '-openshift-master'][0] }}"
      groups: oo_first_master
      ansible_ssh_user: "{{ deployment_vars[deployment_type].ssh_user | default(ansible_ssh_user, true) }}"
      ansible_sudo: "{{ deployment_vars[deployment_type].sudo }}"
    when: "'tag_env-host-type-{{ cluster_id }}-openshift-master' in groups"

- include: ../../common/openshift-cluster/config.yml
  vars:
    openshift_cluster_id: "{{ cluster_id }}"
    openshift_debug_level: 4
    openshift_deployment_type: "{{ deployment_type }}"
    openshift_first_master: "{{ groups.oo_first_master.0 }}"
    openshift_hostname: "{{ gce_private_ip }}"
